### ISSUE TITLE
Keyword tracker

### ISSUE THREAD

**Issue by thafoxey** [Vencord/plugin-requests#172]
### Plugin Description

A plugin that notifies you when a specific keyword/phrase has been mentioned. Great for games that implement discord based matchmaking.

### Existing Plugin for other mod

https://betterdiscord.app/plugin/KeywordTracker

### Request Agreement

- [X] I read the above and made sure my plugin is possible and allowed
- [X] I checked the [existing plugins](https://vencord.dev/plugins) and made sure my plugin doesn't already exist
- [X] I [searched the existing issues](https://github.com/Vencord/plugin-requests/issues?q=is%3Aissue) and made sure a similar request doesn't already exist

**Comment by nvhhr** [comment]
https://github.com/Vendicated/Vencord/pull/1960
